language: go

notifications:
  email: false

install:
  - go get github.com/spf13/hugo

script:
  - if [ "$TRAVIS_BRANCH" = "development" ]; then hugo -D -b $DEV_BASE_URL; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then hugo; fi

deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY
    secret_access_key: $SECRET_KEY
    bucket: $PROD_BUCKET
    skip_cleanup: true
    region: $REGION
    local_dir: "public"
    on:
      branch: "master"
  - provider: s3
    access_key_id: $ACCESS_KEY
    secret_access_key: $SECRET_KEY
    bucket: $DEV_BUCKET
    skip_cleanup: true
    region: $REGION
    local_dir: "public"
    on:
      branch: "development"