baseURL = "http://swhalley.ca/"
languageCode = "en-us"
theme = "blog-style"
enableEmoji = true

title = "Sean's Thoughts"

[params]
subtitle = "Development made \"easy\""
author = "Sean Whalley"

image = "img/me.jpeg"
about = [ 
  "I am a Software Developer who has been working in the field for many years now. My focus in the world is to teach others about clean code and that keeping things simple is more effective then being the smartest person in the room. Over the years I have had the chance to work with very talented people and soaked up a lot of knowledge during that time.",
  "Anyone can be an XX developer, coding isn't hard. The transition to a software developer that writes good code is a constant battle. There is a long road with a lot of learning plateaus. Finding the right direction to continue moving forward with your career is never easy.",
  "I am a classic scatter brain. The thoughts you read will reflect this. But if you can read between the crazy, you will learn that I have a lot to teach. I keep things simple because anything else causes unneeded stress.",
  "My blog is a collection of the thoughts that swirl around in my head. I make every effort to attribute my thoughts back to the people who have influenced me. But if I miss you, reach out and I would be happy to give credit where credit is due."  
]

about_ext = [
  "Some more to add"
]

about_thanks = "Thanks for reading,"

[communication]
email = "swhalley at gmail.com"
github = "swhalley"
twitter = "seanWhalley21"

[[menu.main]]
  name = "Home"
  weight = 1
  url = "/"

[[menu.main]]
  name = "See All"
  weight = 3
  url = "/post"

[[menu.main]]
  name = "Work"
  weight = 10
  url = "https://github.com/swhalley"

[[menu.main]]
  name = "About"
  weight = 8
  url = "/about"